FROM kkarczmarczyk/node-yarn:6.9

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN yarn

# Bundle app source
COPY . /usr/src/app
RUN yarn run build
EXPOSE 5000
CMD [ "yarn", "run", "serve" ]
